language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

git:
  depth: 2

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - travis_retry composer install

after_success:
  - travis_retry php vendor/bin/php-coveralls

script: vendor/bin/phpunit -c ./phpunit.xml.dist
